---
- hosts: all
  gather_facts: true
  tasks:
    - name: "Deploy Netbox Instance"
      include_role:
        name: netbox-manage
      tags:
        - deploy
        - upgrade
        - backup
        - restore
        