---
# tasks file for netbox-deploy
- name: "Install Pre-Reqs"
  include_tasks:
    file: "{{ansible_distribution | lower}}_pre-reqs.yml"
    apply:
        tags:
          - deploy
          - upgrade
          - backup
          - restore
  tags:
    - deploy
    - upgrade
    - backup
    - restore
  
- name: "Deploy Netbox"
  include_tasks:
    file: "deploy/netbox_deploy.yml"
    apply:
      tags:
        - deploy
  tags:
    - deploy
    
- name: "Backup Netbox"
  include_tasks:
    file: "backup/netbox_backup.yml"
    apply:
      tags:
        - backup
  tags:
    - backup

- name: "Restore Netbox"
  include_tasks:
    file: "restore/netbox_restore.yml"
    apply:
      tags:
        - restore
  tags:
    - restore

- name: "Upgrade Netbox"
  include_tasks:
    file: "upgrade/netbox_update.yml"
    apply:
      tags:
        - upgrade
  tags:
    - upgrade